### PR TITLE
Changed the aws api version to 2015-10-01 to support ec2 async adapte…

### PR DESCRIPTION
**Pull request by sprakash28**

### CODE REVIEW

**Comment by servicemesh-autobuild** [comment]
:white_check_mark: Build was successful :tada:


http://ci.servicemesh.com:8080/job/com.servicemesh.agility.adapters.core.aws-prb/1/

**Comment by servicemesh-autobuild** [comment]
:white_check_mark: Build was successful :tada:


http://ci.servicemesh.com:8080/job/com.servicemesh.agility.adapters.core.aws-prb/1/

**Comment by Behnke19** [comment]
retest

**Comment by servicemesh-autobuild** [comment]
:white_check_mark: Build was successful :tada:


http://ci.servicemesh.com:8080/job/com.servicemesh.agility.adapters.core.aws-prb/2/

**Comment by Behnke19** [comment]
retest

**Comment by servicemesh-autobuild** [comment]
:white_check_mark: Build was successful :tada:


http://ci.servicemesh.com:8080/job/com.servicemesh.agility.adapters.core.aws-prb/5/

**Pull request merged**
